# Generated by Django 3.1 on 2020-10-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200910_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('kgs', 'KGS'), ('rub', 'RUB'), ('usd', 'USD')], default='kgs', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('kg', 'Kyrgyz'), ('ru', 'Russian')], default='kg', max_length=2),
        ),
    ]
