# Generated by Django 3.1 on 2020-09-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversations',
            options={'verbose_name': 'Conversation'},
        ),
    ]
